name: flutter_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.0
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.3.0
  cupertino_icons: ^1.0.6
  firebase_analytics: ^11.1.0
  firebase_core: ^3.1.1
  firebase_storage: ^12.2.0
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  intl: ^0.19.0
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^3.0.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/banner/
    - assets/images/gallery/

    - assets/images/e9b4486e5cb972cdb482690080dfcd70.png
    - assets/images/horarios1.jpg
    - assets/images/horarios2.jpg
    - assets/images/maps.png
    - assets/images/rectangl.png
    - assets/images/rectangle.png
    - assets/images/rectangle_1.png
    - assets/images/rectangle_3.png
    - assets/images/rectangle_4.png
    - assets/images/rectangle_5.png
    - assets/images/rectangle_6.png
    - assets/images/rectangle_7.png
    - assets/images/rectangle_9.png
    - assets/images/rectangle_10.png
    - assets/images/rectangle_11.png
    - assets/images/rectangle_13.png
    - assets/images/rectangle_15.png
    - assets/images/rectangle_16.png
    - assets/images/rectangle_18.png
    - assets/images/rectangle_20.jpeg
    - assets/images/rectangle_20.png
    - assets/images/rectangle_22.png
    - assets/images/rectangle_23.jpeg
    - assets/images/fut/fut1.jpg
    - assets/images/fut/fut2.jpg
    - assets/images/fut/fut3.jpg
    - assets/images/fut/fut4.jpg
    - assets/images/fut/fut5.jpg
    - assets/images/fut/fut6.jpg
    - assets/images/fut/fut7.jpg
    - assets/images/fut/fut8.jpg
    - assets/images/fut/fut9.jpg
    - assets/images/fut/fut10.jpg
    - assets/images/box/box1.jpg
    - assets/images/box/box2.jpg
    - assets/images/box/box3.jpg
    - assets/images/box/box4.jpg
    - assets/images/box/box5.jpg
    - assets/images/box/box6.jpg
    - assets/images/box/box7.jpg
    - assets/images/box/box8.jpg
    - assets/images/box/box9.jpg
    - assets/images/estre/estre.jpg
    - assets/images/estre/estre1.jpg
    - assets/images/estre/estre2.jpg
    - assets/images/estre/estre3.jpg
    - assets/images/estre/estre4.jpg
    - assets/images/luchas/lucha1.jpg
    - assets/images/luchas/lucha2.jpg
    - assets/images/luchas/lucha3.jpg
    - assets/images/luchas/lucha4.jpg
    - assets/images/luchas/lucha5.jpg
    - assets/images/luchas/lucha6.jpg
    - assets/images/luchas/lucha7.jpg
    - assets/images/rectangle_24.png
    - assets/images/horarios1.png
    - assets/images/horarios2.png
    - assets/images/pots/box/box1.png
    - assets/images/pots/box/box2.png
    - assets/images/pots/box/box3.png
    - assets/images/pots/box/box5.png
    - assets/images/pots/box/box6.png
    - assets/images/pots/box/box7.png
    - assets/images/pots/box/box8.png
    - assets/images/pots/box/box9.png
    - assets/images/pots/fut/fut1.png
    - assets/images/pots/fut/fut2.png
    - assets/images/pots/fut/fut3.png
    - assets/images/pots/fut/fut4.png
    - assets/images/pots/fut/fut5.png
    - assets/images/pots/fut/fut6.png
    - assets/images/pots/fut/fut7.png
    - assets/images/pots/fut/fut8.png
    - assets/images/pots/fut/fut9.png
    - assets/images/pots/fut/fut10.png
    - assets/images/pots/luchas/lucha2.png
    - assets/images/pots/luchas/lucha3.png
    - assets/images/pots/luchas/lucha4.png
    - assets/images/pots/luchas/lucha6.png
    - assets/images/pots/luchas/lucha7.png
    - assets/images/pots/estre/estre1.png
    - assets/images/pots/estre/estre2.png
    - assets/images/pots/estre/estre3.png
    - assets/images/pots/estre/estre4.png
    - assets/images/load.gif
    - assets/images/losniños.png
    - assets/images/gallery/meet1.jpg
    - assets/images/gallery/meet2.jpg
    - assets/images/gallery/meet3.jpg
    - assets/images/gallery/meet4.jpg
    - assets/images/gallery/meet5.jpg
    - assets/images/gallery/meet6.jpg
    - assets/images/gallery/meet7.jpg
    - assets/images/gallery/meet8.jpg
    - assets/images/gallery/meet9.jpg
    - assets/images/gallery/meet11.png
    - assets/images/gallery/meet13.jpg
    - assets/images/gallery/meet14.jpg
    - assets/images/gallery/meet15.jpg
    - assets/images/gallery/meet16.jpg
    - assets/images/gallery/meet17.jpg
    - assets/images/gallery/meet18.jpg
    - assets/images/gallery/meet19.jpg
    - assets/images/gallery/meet20.jpg
    - assets/images/gallery/meet21.jpg
    - assets/images/gallery/meet22.jpg
    - assets/images/gallery/meet23.jpg
    - assets/images/gallery/meet24.jpg
    - assets/images/gallery/meet25.jpg
    - assets/images/gallery/meet26.jpg
    - assets/images/gallery/meet27.jpg
    - assets/images/gallery/meet28.jpg
    - assets/images/gallery/meet29.jpg
    - assets/images/gallery/meet30.jpg
    - assets/images/gallery/meet31.jpg
    - assets/images/gallery/meet32.jpg
    - assets/images/gallery/meet33.jpg
    - assets/images/gallery/meet34.jpg
    - assets/images/gallery/meet35.jpg
    - assets/images/gallery/meet36.jpg
    - assets/images/gallery/meet37.jpg
    - assets/images/gallery/meet38.jpg
    - assets/images/gallery/meet39.jpg
    - assets/images/gallery/meet40.jpg
    - assets/images/gallery/meet41.jpg
    - assets/images/gallery/meet42.jpg
    - assets/images/gallery/meet43.jpg
    - assets/images/gallery/meet44.jpg
    - assets/images/gallery/meet45.jpg
    - assets/images/gallery/meet46.jpg
    - assets/images/gallery/meet47.jpg
    - assets/images/gallery/meet48.jpg
    - assets/images/gallery/meet49.jpg
    - assets/images/gallery/meet50.jpg
    - assets/images/gallery/meet51.jpg
    - assets/images/gallery/meet52.jpg
    - assets/images/gallery/meet53.jpg
    - assets/images/gallery/meet54.jpg
    - assets/images/gallery/meet55.jpg
    - assets/images/gallery/meet56.jpg
    - assets/images/gallery/meet57.jpg
    - assets/images/gallery/meet58.jpg
    - assets/images/gallery/meet59.jpg
    - assets/images/gallery/meet60.jpg
    - assets/images/gallery/meet61.jpg
    - assets/images/gallery/meet62.jpg
    - assets/images/gallery/meet63.jpg
    - assets/images/gallery/meet64.jpg
    - assets/images/gallery/meet65.jpg
    - assets/images/gallery/meet66.jpg
    - assets/images/gallery/meet67.jpg
    - assets/images/gallery/meet68.jpg
    - assets/images/gallery/meet69.jpg
    - assets/images/gallery/meet70.jpg
    - assets/images/gallery/meet71.jpg
    - assets/images/gallery/meet72.jpg
    - assets/images/gallery/meet73.jpg
    - assets/images/gallery/meet74.jpg
    - assets/images/gallery/meet75.jpg
